### PR TITLE
@PlatformIO Library Registry manifest file: add "include" and "examples" fields

### PR DESCRIPTION
**Pull request by ivankravets**
- This library in Web Registry: http://platformio.org/#!/lib/show/444/Buttons
- Specification: [PlatformIO Library Manager](http://docs.platformio.org/en/latest/librarymanager/index.html)
- Integration: [IDE Integration](http://docs.platformio.org/en/latest/ide.html)

### CODE REVIEW

**Comment by r89m** [comment]
Thanks for this Ivan, I'm still pretty new to PlatformIO

**Comment by ivankravets** [comment]
@shaggythesheep have you tried @PlatformIO already?

**Comment by r89m** [comment]
Not yet, but it looks really interesting.

Is there a way to update the web listing (as it's currently out of sync with the repo) or does it just happen every 24hrs or similar.

**Comment by ivankravets** [comment]
> Is there a way to update the web listing (as it's currently out of sync with the repo) or does it just happen every 24hrs or similar.

Yes, libraries update every 24h. it seems that your lib is already updated http://platformio.org/#!/lib/show/444/Buttons

**Comment by r89m** [comment]
Awesome, thanks.

Just noticed it's only picking up one BasicUse.ino example, but there's three - one in PushButton, CapacitiveButton and MPR121Button - any tips? Cheers

**Comment by ivankravets** [comment]
@PlatformIO ignores examples with the same names.

**Comment by r89m** [comment]
Ah right, is that a bug or expected behaviour?

**Comment by ivankravets** [comment]
This is expected behaviour

**Comment by r89m** [comment]
I'll look into renaming them then

**Comment by ivankravets** [comment]
I'm agree that this is my issue. However, I pack all examples into the one directory without saving path's structure. Here they overwrite each other. Navigation over the examples is based on "example file name". See:
- http://platformio.org/#!/lib/examples?query=buttons&page=1
- http://platformio.org/#!/lib/show/444/Buttons?example=FastRead.ino

**Pull request merged**
